# 表示该docker-compose.yml文件使用的是Version 3 file format
version: '3.7'
services:
  magic-filebeat:
     # replace username/repo:tag with your name and image details
    image: docker.elastic.co/beats/filebeat:6.5.4
    deploy:
      # 可以被外界客户端连接 vip ,dnsrr 内部网络之间连接
      #endpoint_mode: vip
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    container_name: magic-filebeat
    hostname: magic-filebeat
    restart: always
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro